name: overlay_lottie
description: A package that overlays a lottie animation over a widget, during the execution of long tasks
version: 1.0.1
homepage: https://github.com/damadenacar/flutter.overlay_lottie

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0